baseURL: "https://massimilianoursignew.netlify.app/"
languageCode: en-us
title: Massimiliano
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: My works
    subtitle: |-
      Here you can find all my Data Ananalysis works done till this moment. You will see line codes, graphs and a description of the what the plot is trying to tell us.
    title: Welcome, this is Massimiliano Ursig's website
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: 25 Hardwick, Lilestone Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mursig.mam2022@london.edu
    enable: yes
    phone:
      - phone: (+39) 3392809973
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Massimiliano
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com/massimilianoursig
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/massimilianoursig
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/massimilianoursig
#      - icon: fa-linkedin
#        label: LinkedIn
#        url: https://www.linkedin.com/in/kostis-christodoulou-285147/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Let's take a look
        url: blogs
#    button2:
#      - name: Sign In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Entrepreneurship
        url: blogs/impresa
#      - name: Elements
#        url: elements.html
      - name: CV
        url: blogs/cv 
    menu: Menu
#    subtitle: By HTML5 Up
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: robert-v-ruggiero-FLMdXg-6rJo-unsplash.jpg
        subtitle: Brief Biography
        title: Who am I?
        url: blogs/aliquam
      - image: pexels-ivan-bertolazzi-2681319.jpg
#        subtitle: Brief Biography
        title: CV
        url: blogs/tempus
      - image: franki-chamaki-1K6IQsQbizI-unsplash.jpg
#        subtitle: Start
        title: LBS work 1
        url: blogs/max
      - image: hunter-harritt-Ype9sdOPdYc-unsplash.jpg
#        subtitle: Nisl Sed Aliquam
        title: LBS work 2
        url: blogs/pane
      - image: pierre-chatel-innocenti-pxoZSTdAzeU-unsplash.jpg
        subtitle: Make it simple
        title: LBS work 3
        url: blogs/massi
      - image: pexels-lukas-590041.jpg
        subtitle: Autonomus Analysis
        title: LBS work 4
        url: blogs/ipsum
  two:
    buttonText: Let's take a look
    enable: yes
    showcase:
      - image: pexels-ivan-bertolazzi-2681319.jpg
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
    title: Keep in touch, evolve your interest 
    url: blogs