---
categories:
- ""
- ""
date: "2017-10-31T22:42:51-05:00"
description: Nullam et orci eu lorem consequat tincidunt vivamus et sagittis magna
  sed nunc rhoncus condimentum sem. In efficitur ligula tate urna. Maecenas massa
  sed magna lacinia magna pellentesque lorem ipsum dolor. Nullam et orci eu lorem
  consequat tincidunt. Vivamus et sagittis tempus.
draft: false
image: hunter-harritt-Ype9sdOPdYc-unsplash.jpg
keywords: ""
slug: pane
title: LBS work 2
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies you need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<p>Run the code below to load the file:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>Notice that, when using this function, we added two options: <code>skip</code> and <code>na</code>.</p>
<ol style="list-style-type: decimal">
<li>The <code>skip=1</code> option is there as the real data table only starts in Row 2, so we need to skip one row.</li>
<li><code>na = "***"</code> option informs R how missing observations in the spreadsheet are coded. When looking at the spreadsheet, you can see that missing data is coded as "***". It is best to specify this here, as otherwise some of the data is not recognized as numeric data.</li>
</ol>
<p>Once the data is loaded, notice that there is a object titled <code>weather</code> in the <code>Environment</code> panel. If you cannot see the panel (usually on the top-right), go to <code>Tools</code> &gt; <code>Global Options</code> &gt; <code>Pane Layout</code> and tick the checkbox next to <code>Environment</code>. Click on the <code>weather</code> object, and the dataframe will pop up on a separate tab. Inspect the dataframe.</p>
<p>For each month and year, the dataframe shows the deviation of temperature from the normal (expected). Further the dataframe is in wide format.</p>
<p>You have two objectives in this section:</p>
<ol style="list-style-type: decimal">
<li><p>Select the year and the twelve month variables from the <code>weather</code> dataset. We do not need the others (J-D, D-N, DJF, etc.) for this assignment. Hint: use <code>select()</code> function.</p></li>
<li><p>Convert the dataframe from wide to ‘long’ format. Hint: use <code>gather()</code> or <code>pivot_longer()</code> function. Name the new dataframe as <code>tidyweather</code>, name the variable containing the name of the month as <code>month</code>, and the temperature deviation values as <code>delta</code>.</p></li>
</ol>
<pre class="r"><code>#Select only year and months
weather_months &lt;- weather %&gt;%
  select(1:13)

#Convert from wide to long
tidyweather &lt;- weather_months %&gt;% 
  pivot_longer(cols= 2:13,
               names_to = &quot;month&quot;,
               values_to = &quot;delta&quot;)

glimpse(tidyweather)</code></pre>
<pre><code>## Rows: 1,704
## Columns: 3
## $ Year  &lt;dbl&gt; 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880~
## $ month &lt;chr&gt; &quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, &quot;~
## $ delta &lt;dbl&gt; -0.34, -0.50, -0.22, -0.29, -0.05, -0.15, -0.17, -0.25, -0.22, -~</code></pre>
<p>Inspect your dataframe. It should have three variables now, one each for</p>
<ol style="list-style-type: decimal">
<li>year,</li>
<li>month, and</li>
<li>delta, or temperature deviation.</li>
</ol>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trendline. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<blockquote>
<p>In the following chunk of code, I used the <code>eval=FALSE</code> argument, which does not run a chunk of code; I did so that you can knit the document before tidying the data and creating a new dataframe <code>tidyweather</code>. When you actually want to run this code and knit your document, you must delete <code>eval=FALSE</code>, <strong>not just here but in all chunks were <code>eval=FALSE</code> appears.</strong></p>
</blockquote>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;
  )</code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Use <code>facet_wrap()</code> to produce a separate scatter plot for each month, again with a smoothing line. Your chart should human-readable labels; that is, each month should be labeled “Jan”, “Feb”, “Mar” (full or abbreviated month names are fine), not <code>1</code>, <code>2</code>, <code>3</code>.</p>
<p><img src="/blogs/homework2_second_draft_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Is the effect of increasing temperature more pronounced in some months?</p>
</blockquote>
<p>Generally, we can see increasing temperature more pronounced in winter months with March showing the highest deviation from expected temperature.</p>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calculates a temperature anomaly, as difference form the base period of 1951-1980. The code below creates a new data frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We remove data before 1800 and before using <code>filter</code>. Then, we use the <code>mutate</code> function to create a new variable <code>interval</code> which contains information on which period each observation belongs to. We can assign the different periods using <code>case_when()</code>.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Inspect the <code>comparison</code> dataframe by clicking on it in the <code>Environment</code> pane.</p>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in. Set <code>fill</code> to <code>interval</code> to group and colour the data by different time periods.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with transparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;         #changing y-axis label to sentence case
  )</code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(
    annual_average_delta = mean(delta, na.rm=TRUE))
    

#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;
  )                         </code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
<p>Your task is to construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package. Recall that the dataframe <code>comparison</code> has already grouped temperature anomalies according to time intervals; we are only interested in what is happening between 2011-present.</p>
<pre class="r"><code>#construct confidence interval using formula
formula_ci &lt;- comparison %&gt;% 
  filter(interval == &quot;2011-present&quot;) %&gt;%
  summarize(
    median_delta = median(delta, na.rm=TRUE),
    mean_delta = mean(delta, na.rm=TRUE),
    sd_delta = sd(delta, na.rm=TRUE),
    count = n(),
    se_delta = sd_delta / sqrt(count),
    t_critical = qt(0.975, count-1),
    lower_ci = mean_delta - t_critical*se_delta,
    upper_ci = mean_delta + t_critical*se_delta)

#print out formula CI
formula_ci</code></pre>
<pre><code>## # A tibble: 1 x 8
##   median_delta mean_delta sd_delta count se_delta t_critical lower_ci upper_ci
##          &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1         1.04       1.06    0.274   132   0.0239       1.98     1.01     1.11</code></pre>
<pre class="r"><code>#set seed before using bootstrap
set.seed(1998)
library(infer)

#construct confidence interval using bootstrap
bootstrap_delta &lt;- comparison %&gt;%
  filter(interval == &quot;2011-present&quot;) %&gt;%
  specify(response = delta) %&gt;%
  generate(reps=1000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;)

bootstrap_ci &lt;- bootstrap_delta %&gt;%
  get_ci(level=0.95, type=&quot;percentile&quot;)

#print out bootstrap CI
bootstrap_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.01     1.11</code></pre>
<blockquote>
<p>What is the data showing us? Please type your answer after (and outside!) this blockquote. You have to explain what you have done, and the interpretation of the result. One paragraph max, please!</p>
</blockquote>
<p>Firstly, in order to get the summary statistics, we use formula to sample data and calculate the mean, standard deviation, standard error and the confidence interval. To confirm our results, we use bootstrap simulation to create 1000 samples of our own and recalculate the simulated sample statistics. 
From the mean of delta of 1.06, we can say that since 2011 till present, the average annual temperature deviation is 1.06 degrees from expected temperature. Looking at the 95% confidence interval, we can say that we are 95% confident that the average annual deviation from expected temperature lies between 1.01 and 1.11. 
From the comparison of sample statistics using formula and bootstrap simulation, both methods give us the same results. </p>
</div>
</div>
<div id="general-social-survey-gss" class="section level1">
<h1>General Social Survey (GSS)</h1>
<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviors, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>In this assignment we analyze data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and you are using a smaller file.</p>
<pre class="r"><code>#read data
gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;))

glimpse(gss)</code></pre>
<pre><code>## Rows: 2,867
## Columns: 7
## $ emailmin &lt;chr&gt; &quot;0&quot;, &quot;30&quot;, &quot;NA&quot;, &quot;10&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;0&quot;, ~
## $ emailhr  &lt;chr&gt; &quot;12&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;2&quot;, &quot;40&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;2&quot;, ~
## $ snapchat &lt;chr&gt; &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;NA&quot;, &quot;No&quot;,~
## $ instagrm &lt;chr&gt; &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;Yes&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;NA&quot;, &quot;No&quot;~
## $ twitter  &lt;chr&gt; &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;No&quot;, &quot;~
## $ sex      &lt;chr&gt; &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Female&quot;, &quot;Female&quot;, &quot;Female&quot;, &quot;Male&quot;,~
## $ degree   &lt;chr&gt; &quot;Bachelor&quot;, &quot;High school&quot;, &quot;Bachelor&quot;, &quot;High school&quot;, &quot;Gradua~</code></pre>
<p>You will also notice that many responses should not be taken into consideration, like “No Answer”, “Don’t Know”, “Not applicable”, “Refused to Answer”.</p>
<p>We will be creating 95% confidence intervals for population parameters. The variables we have are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</li>
<li><code>sex</code>: Female - Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>Can we estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not. If the recorded value was NA for both of these questions, the value in your new variable should also be NA.</li>
</ol>
<pre class="r"><code>snap_insta &lt;- gss %&gt;%
  mutate(snap_insta = if_else(snapchat == &quot;NA&quot; &amp; instagrm == &quot;NA&quot;, &quot;NA&quot;, 
                              if_else(snapchat==&quot;Yes&quot; | instagrm == &quot;Yes&quot;, &quot;Yes&quot;, &quot;No&quot;)))

snap_insta</code></pre>
<pre><code>## # A tibble: 2,867 x 8
##    emailmin emailhr snapchat instagrm twitter sex    degree         snap_insta
##    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;          &lt;chr&gt;     
##  1 0        12      NA       NA       NA      Male   Bachelor       NA        
##  2 30       0       No       No       No      Male   High school    No        
##  3 NA       NA      No       No       No      Male   Bachelor       No        
##  4 10       0       NA       NA       NA      Female High school    NA        
##  5 NA       NA      Yes      Yes      No      Female Graduate       Yes       
##  6 0        2       No       Yes      No      Female Junior college Yes       
##  7 0        40      NA       NA       NA      Male   High school    NA        
##  8 NA       NA      Yes      Yes      No      Female High school    Yes       
##  9 0        0       NA       NA       NA      Male   High school    NA        
## 10 NA       NA      No       No       No      Male   Junior college No        
## # ... with 2,857 more rows</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</li>
</ol>
<pre class="r"><code>snap_insta %&gt;%
  filter(snap_insta != &quot;NA&quot;) %&gt;%
  summarize(
    Proportion_Insta_Snap = count(snap_insta==&quot;Yes&quot;) / n())</code></pre>
<pre><code>## # A tibble: 1 x 1
##   Proportion_Insta_Snap
##                   &lt;dbl&gt;
## 1                 0.375</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Using the CI formula for proportions, please construct 95% CIs for men and women who used either Snapchat or Instagram</li>
</ol>
<pre class="r"><code># CI for Male population
male_proportion &lt;- snap_insta %&gt;%
  filter(sex == &quot;Male&quot;, snap_insta != &quot;NA&quot;) %&gt;%
  summarize(
    proportion = count(snap_insta == &quot;Yes&quot;)/n(),
    se = sqrt((proportion*(1 - proportion)/n())),
    lower_ci = proportion - 1.96*se, #we are using normal distribution to approximate
                                     #binomial distribution and directly use 1.96 as the critical value
    upper_ci = proportion + 1.96*se) %&gt;% 
  knitr::kable(caption = &quot;95% CI for men who used either Snapchat or Instagram&quot;)

# CI for Female population
female_proportion &lt;- snap_insta %&gt;%
  filter(sex == &quot;Female&quot;, snap_insta != &quot;NA&quot;) %&gt;%
  summarize(
    proportion = count(snap_insta == &quot;Yes&quot;)/n(),
    se = sqrt((proportion*(1 - proportion)/n())),
    lower_ci = proportion - 1.96*se,
    upper_ci = proportion + 1.96*se) %&gt;% 
  knitr::kable(caption = &quot;95% CI for women who used either Snapchat or Instagram&quot;)

#print out CIs
male_proportion</code></pre>
<table>
<caption>(#tab:95% CI for men and women using snap or insta)95% CI for men who used either Snapchat or Instagram</caption>
<thead>
<tr class="header">
<th align="right">proportion</th>
<th align="right">se</th>
<th align="right">lower_ci</th>
<th align="right">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.318</td>
<td align="right">0.019</td>
<td align="right">0.281</td>
<td align="right">0.356</td>
</tr>
</tbody>
</table>
<pre class="r"><code>female_proportion</code></pre>
<table>
<caption>(#tab:95% CI for men and women using snap or insta)95% CI for women who used either Snapchat or Instagram</caption>
<thead>
<tr class="header">
<th align="right">proportion</th>
<th align="right">se</th>
<th align="right">lower_ci</th>
<th align="right">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.419</td>
<td align="right">0.018</td>
<td align="right">0.384</td>
<td align="right">0.454</td>
</tr>
</tbody>
</table>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>Can we estimate the <em>population</em> proportion of Twitter users by education level in 2016?.</p>
<p>There are 5 education levels in variable <code>degree</code> which, in ascneding order of years of education, are Lt high school, High School, Junior college, Bachelor, Graduate.</p>
<ol style="list-style-type: decimal">
<li>Turn <code>degree</code> from a character variable into a factor variable. Make sure the order is the correct one and that levels are not sorted alphabetically which is what R by default does. Create a new variable, <code>bachelor_graduate</code> that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree. As before, if the recorded value for either was NA, the value in your new variable should also be NA.</li>
</ol>
<pre class="r"><code>gss_degree &lt;- gss %&gt;%
  mutate(
    degree = factor(degree, order=TRUE, levels = c(&quot;Lt high school&quot;, &quot;High School&quot;, &quot;Junior college&quot;, &quot;Bachelor&quot;, &quot;Graduate&quot;)), 
    bachelor_graduate = if_else(degree&gt;=&quot;Bachelor&quot;, &quot;Yes&quot;, &quot;No&quot;)
  )
  
glimpse(gss_degree)</code></pre>
<pre><code>## Rows: 2,867
## Columns: 8
## $ emailmin          &lt;chr&gt; &quot;0&quot;, &quot;30&quot;, &quot;NA&quot;, &quot;10&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;N~
## $ emailhr           &lt;chr&gt; &quot;12&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;2&quot;, &quot;40&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;N~
## $ snapchat          &lt;chr&gt; &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;N~
## $ instagrm          &lt;chr&gt; &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;Yes&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;~
## $ twitter           &lt;chr&gt; &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;No&quot;, &quot;NA&quot;~
## $ sex               &lt;chr&gt; &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Female&quot;, &quot;Female&quot;, &quot;Female&quot;~
## $ degree            &lt;ord&gt; Bachelor, NA, Bachelor, NA, Graduate, Junior college~
## $ bachelor_graduate &lt;chr&gt; &quot;Yes&quot;, NA, &quot;Yes&quot;, NA, &quot;Yes&quot;, &quot;No&quot;, NA, NA, NA, &quot;No&quot;,~</code></pre>
<ol style="list-style-type: decimal">
<li>Calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>#tidy data and count
twitter_bachelor &lt;- gss_degree %&gt;%
  filter(bachelor_graduate == &quot;Yes&quot;, twitter != &quot;NA&quot;) %&gt;%
  group_by(bachelor_graduate, twitter) %&gt;%
  count()

#calculate proportions
twitter_bachelor_proportions &lt;- twitter_bachelor %&gt;%
  pivot_wider(names_from = twitter, values_from = n) %&gt;%
  summarize(
    bachelor_twitter_users = Yes/sum(Yes,No),
    bachelor_non_twitter_users = 1 - bachelor_twitter_users
  ) %&gt;%
  select(c(&quot;bachelor_graduate&quot;, &quot;bachelor_twitter_users&quot;, &quot;bachelor_non_twitter_users&quot;)) %&gt;% 
  knitr::kable(caption = &quot;proportions for bachelor graduates using and not using Twitter&quot;)
  
twitter_bachelor_proportions</code></pre>
<table>
<caption>(#tab:proportion of bachelor graduates using twitter)proportions for bachelor graduates using and not using Twitter</caption>
<thead>
<tr class="header">
<th align="left">bachelor_graduate</th>
<th align="right">bachelor_twitter_users</th>
<th align="right">bachelor_non_twitter_users</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Yes</td>
<td align="right">0.233</td>
<td align="right">0.767</td>
</tr>
</tbody>
</table>
<ol start="2" style="list-style-type: decimal">
<li>Using the CI formula for proportions, please construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>#construct CI using formula
twitter_bachelor_95 &lt;- twitter_bachelor %&gt;%
  mutate(
    count = sum(twitter_bachelor$n),
    proportion = n/count,
    se_twitter = sqrt((proportion * (1-proportion))/count),
    lower_ci =  proportion - 1.96*se_twitter,
    upper_ci= proportion + 1.96*se_twitter) %&gt;% 
  select(c(&quot;bachelor_graduate&quot;, &quot;twitter&quot;, &quot;lower_ci&quot;, &quot;upper_ci&quot;)) %&gt;% 
  knitr::kable(caption = &quot;95% CIs for bachelor graduates who use and do not use Twitter&quot;)

twitter_bachelor_95</code></pre>
<table>
<caption>(#tab:95% CI for bachelor_graduate)95% CIs for bachelor graduates who use and do not use Twitter</caption>
<thead>
<tr class="header">
<th align="left">bachelor_graduate</th>
<th align="left">twitter</th>
<th align="right">lower_ci</th>
<th align="right">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Yes</td>
<td align="left">No</td>
<td align="right">0.729</td>
<td align="right">0.804</td>
</tr>
<tr class="even">
<td align="left">Yes</td>
<td align="left">Yes</td>
<td align="right">0.196</td>
<td align="right">0.271</td>
</tr>
</tbody>
</table>
<blockquote>
<ol start="3" style="list-style-type: decimal">
<li>Do these two Confidence Intervals overlap?</li>
</ol>
</blockquote>
<p>No, these two confidence intervals do not overlap. There is a significant difference between bachelor graduates who do and who do not use Twitter. </p>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Can we estimate the <em>population</em> parameter on time spent on email weekly?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable called <code>email</code> that combines <code>emailhr</code> and <code>emailmin</code> to reports the number of minutes the respondents spend on email weekly.</li>
</ol>
<pre class="r"><code>email_time &lt;- gss %&gt;% 
  mutate(
    email = as.numeric(emailhr) * 60 + as.numeric(emailmin))

email_time</code></pre>
<pre><code>## # A tibble: 2,867 x 8
##    emailmin emailhr snapchat instagrm twitter sex    degree         email
##    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;          &lt;dbl&gt;
##  1 0        12      NA       NA       NA      Male   Bachelor         720
##  2 30       0       No       No       No      Male   High school       30
##  3 NA       NA      No       No       No      Male   Bachelor          NA
##  4 10       0       NA       NA       NA      Female High school       10
##  5 NA       NA      Yes      Yes      No      Female Graduate          NA
##  6 0        2       No       Yes      No      Female Junior college   120
##  7 0        40      NA       NA       NA      Male   High school     2400
##  8 NA       NA      Yes      Yes      No      Female High school       NA
##  9 0        0       NA       NA       NA      Male   High school        0
## 10 NA       NA      No       No       No      Male   Junior college    NA
## # ... with 2,857 more rows</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Visualize the distribution of this new variable. Find the mean and the median number of minutes respondents spend on email weekly.</li>
</ol>
<pre class="r"><code>ggplot(email_time, 
       aes(x= email))+
  geom_density()+
  theme_bw() +
  labs (
    title = &quot;Time Spent on email&quot;,
    x     = &quot;Minutes spent on email weekly&quot;)                         </code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/distribution%20of%20email%20time-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#calculate mean and median
email_time %&gt;% 
  summarise(mean_email_time = mean(email, na.rm=TRUE),
            median_email_time = median(email, na.rm=TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 2
##   mean_email_time median_email_time
##             &lt;dbl&gt;             &lt;dbl&gt;
## 1            417.               120</code></pre>
<blockquote>
<p>Is the mean or the median a better measure of the typical among of time Americans spend on email weekly? Why?</p>
</blockquote>
<p>The median is a better measure since the density of time spent is significantly right skewed and extreme values in the right tail pull the mean away from the center. 
The median is less affected by such extreme values. </p>
<ol start="3" style="list-style-type: decimal">
<li>Using the <code>infer</code> package, calculate a 95% bootstrap confidence interval for the mean amount of time Americans spend on email weekly. Interpret this interval in context of the data, reporting its endpoints in “humanized” units (e.g. instead of 108 minutes, report 1 hr and 8 minutes).</li>
</ol>
<pre class="r"><code>#construct CI using bootstrap
set.seed(1998)
library(infer)

bootstrap_email &lt;- email_time %&gt;%
  specify(response = email) %&gt;%
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;)

bootstrap_ci &lt;- bootstrap_email %&gt;%
  get_ci(level = 0.95, type = &quot;percentile&quot;) %&gt;% 
  #&quot;humanize&quot; time units to [__ hrs __ mins]
  mutate(lower_ci = paste(paste(385 %/% 60, &quot;hrs&quot;), paste(385 %% 60, &quot;mins&quot;)),
         upper_ci = paste(paste(448 %/% 60, &quot;hrs&quot;), paste(448 %% 60, &quot;mins&quot;)))
bootstrap_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci      upper_ci     
##   &lt;chr&gt;         &lt;chr&gt;        
## 1 6 hrs 25 mins 7 hrs 28 mins</code></pre>
<blockquote>
<p>If you get a result that seems a bit odd, discuss why you think this might be the case.</p>
</blockquote>
<p>Since we are calculating weekly usage on email, roughly 7 hours per week or 1 hour per day seems normal. </p>
<blockquote>
<p>Would you expect a 99% confidence interval to be wider or narrower than the interval you calculated above? Explain your reasoning.</p>
</blockquote>
<p>Increasing the confidence level to 99% will increase the margin of error and result in a wider interval. 
In order to be more confident that the true population mean would lie within the reported interval, we need to allow for more values in the interval.</p>
</div>
</div>
<div id="bidens-approval-margins" class="section level1">
<h1>Biden’s Approval Margins</h1>
<p>As we saw in class, fivethirtyeight.com has detailed data on <a href="https://projects.fivethirtyeight.com/biden-approval-ratings">all polls that track the president’s approval</a></p>
<pre class="r"><code># Import approval polls data directly off fivethirtyeight website
approval_polllist &lt;- read_csv(&#39;https://projects.fivethirtyeight.com/biden-approval-data/approval_polllist.csv&#39;) 

glimpse(approval_polllist)</code></pre>
<pre><code>## Rows: 1,601
## Columns: 22
## $ president           &lt;chr&gt; &quot;Joseph R. Biden Jr.&quot;, &quot;Joseph R. Biden Jr.&quot;, &quot;Jos~
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;~
## $ modeldate           &lt;chr&gt; &quot;9/19/2021&quot;, &quot;9/19/2021&quot;, &quot;9/19/2021&quot;, &quot;9/19/2021&quot;~
## $ startdate           &lt;chr&gt; &quot;1/31/2021&quot;, &quot;2/1/2021&quot;, &quot;2/1/2021&quot;, &quot;2/2/2021&quot;, &quot;~
## $ enddate             &lt;chr&gt; &quot;2/2/2021&quot;, &quot;2/3/2021&quot;, &quot;2/3/2021&quot;, &quot;2/4/2021&quot;, &quot;2~
## $ pollster            &lt;chr&gt; &quot;YouGov&quot;, &quot;Rasmussen Reports/Pulse Opinion Researc~
## $ grade               &lt;chr&gt; &quot;B+&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;A-&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B~
## $ samplesize          &lt;dbl&gt; 1500, 1500, 15000, 15000, 1429, 1500, 1005, 15000,~
## $ population          &lt;chr&gt; &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;a~
## $ weight              &lt;dbl&gt; 1.0856, 0.3308, 0.2786, 0.2507, 2.0760, 0.3086, 0.~
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
## $ approve             &lt;dbl&gt; 46, 52, 54, 54, 49, 49, 57, 54, 50, 54, 60, 59, 51~
## $ disapprove          &lt;dbl&gt; 38, 46, 33, 34, 39, 48, 34, 34, 47, 34, 32, 35, 46~
## $ adjusted_approve    &lt;dbl&gt; 47.3, 54.4, 52.5, 52.5, 49.6, 51.4, 55.9, 52.5, 52~
## $ adjusted_disapprove &lt;dbl&gt; 38.3, 40.1, 36.3, 37.3, 39.1, 42.1, 35.1, 37.3, 41~
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~
## $ tracking            &lt;lgl&gt; NA, TRUE, TRUE, TRUE, NA, TRUE, NA, TRUE, TRUE, TR~
## $ url                 &lt;chr&gt; &quot;https://docs.cdn.yougov.com/460mactkmh/econTabRep~
## $ poll_id             &lt;dbl&gt; 74332, 74338, 74366, 74367, 74348, 74347, 74345, 7~
## $ question_id         &lt;dbl&gt; 139593, 139642, 139733, 139734, 139668, 139654, 13~
## $ createddate         &lt;chr&gt; &quot;2/3/2021&quot;, &quot;2/4/2021&quot;, &quot;2/11/2021&quot;, &quot;2/11/2021&quot;, ~
## $ timestamp           &lt;chr&gt; &quot;13:37:08 19 Sep 2021&quot;, &quot;13:37:08 19 Sep 2021&quot;, &quot;1~</code></pre>
<pre class="r"><code># Use `lubridate` to fix dates, as they are given as characters.
approval_polllist &lt;- approval_polllist %&gt;% 
  mutate(enddate = mdy(enddate))</code></pre>
<div id="create-a-plot" class="section level2">
<h2>Create a plot</h2>
<p>What I would like you to do is to calculate the average net approval rate (approve- disapprove) for each week since he got into office. I want you plot the net approval, along with its 95% confidence interval. There are various dates given for each poll, please use <code>enddate</code>, i.e., the date the poll ended.</p>
<p>Also, please add an orange line at zero. Your plot should look like this:</p>
<p><img src="C:/Users/ursig/OneDrive/Desktop/Statistics_LBS/new_website/images/biden_approval_margin.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#tidy data and calculate CI using formula
net_approval &lt;- approval_polllist %&gt;% 
  filter(!is.na(subgroup)) %&gt;%
  #using lubridate to get week number
  mutate(week = isoweek(enddate),
         net_approval_day = approve - disapprove) %&gt;% 
  group_by(subgroup, week) %&gt;%
  summarise(mean_net_approval = mean(net_approval_day),
            sd_net_approval = sd(net_approval_day),
            count = n(),
            se_twitter = sd_net_approval / sqrt(count),
            t_critical = qt(0.975, count - 1),
            lower_ci =  mean_net_approval - t_critical*se_twitter,
            upper_ci = mean_net_approval + t_critical*se_twitter)</code></pre>
<pre class="r"><code>#plot Biden&#39;s weekly net approval rate
ggplot(net_approval, 
       aes(x= week, 
           y= mean_net_approval)) +
  geom_line(color = &quot;red&quot;)+
  geom_point(color = &quot;red&quot;)+
  geom_smooth(color = &quot;blue&quot;,
              level = 0,
              size = 1)+
  #add orange line at zero
  geom_hline(yintercept=0, 
             color = &quot;orange&quot;, 
             size = 2)+
  theme_bw()+
  #add confidence band using calculated CI
  geom_ribbon(aes(ymin = lower_ci, 
                  ymax = upper_ci),
              alpha=0.3,
              fill = &quot;grey&quot;,
              color = &quot;red&quot;) + 
  labs(
    title = &quot;Estimating Approval Margin (approve-disapprove) for Joe Biden&quot;,
    subtitle = &quot;Weekly average of all polls by different subgroups&quot;,
    x = &quot;Week of the year&quot;,
    y = &quot;Average Approval Margin (approve-disapprove)&quot;)+
  #differentiate between Adults, All polls, Voters 
  facet_wrap(vars(subgroup))+
  scale_y_continuous(breaks=seq(-15,10,2.5))</code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/Biden%20net%20approval%20rate%20plot-1.png" width="1344" style="display: block; margin: auto;" /></p>
</div>
<div id="compare-confidence-intervals" class="section level2">
<h2>Compare Confidence Intervals</h2>
<p>Compare the confidence intervals for <code>week 4</code> and <code>week 25</code>.</p>
<pre class="r"><code>net_approval_4_25 &lt;- net_approval %&gt;% 
  filter(week %in% c(4, 25)) %&gt;% 
  mutate(
    ci_width = upper_ci - lower_ci) %&gt;% 
  select(subgroup, week, lower_ci, upper_ci, ci_width)

net_approval_4_25</code></pre>
<pre><code>## # A tibble: 3 x 5
## # Groups:   subgroup [3]
##   subgroup   week lower_ci upper_ci ci_width
##   &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Adults       25    12.0      16.5     4.57
## 2 All polls    25     8.57     13.7     5.08
## 3 Voters       25     3.61     10.5     6.85</code></pre>
<blockquote>
<p>Can you explain what’s going on? One paragraph would be enough.</p>
</blockquote>
<p>From the results, we can clearly see that for all subgroups, the confidence interval for Biden’s net approval rate has been narrower from week 4 to week 25. Especially for Voters subgroup, the width confidence interval has been drastically decreased from 16.84 to 6.85. We assume this is because as after Biden has been elected for a longer period of time in week 25 (almost half a year), all adults including his voters would become more clear about their approval or disapproval to the president. After Americans took over 25-week time to evaluate their new elected president, they would probably have a clearer attitude towards Biden’s policy changes, administration and national strategies. These clearer perceptions then result in this decreasing confidence interval trend.</p>
</div>
</div>
<div id="gapminder-revisited" class="section level1">
<h1>Gapminder revisited</h1>
<p>Recall the <code>gapminder</code> data frame from the gapminder package. That data frame contains just six columns from the larger <a href="https://www.gapminder.org/data/">data in Gapminder World</a>. In this part, you will join a few dataframes with more data than the ‘gapminder’ package. Specifically, you will look at data on</p>
<ul>
<li>Life expectancy at birth (life_expectancy_years.csv)</li>
<li>GDP per capita in constant 2010 US$ (<a href="https://data.worldbank.org/indicator/NY.GDP.PCAP.KD" class="uri">https://data.worldbank.org/indicator/NY.GDP.PCAP.KD</a>)</li>
<li>Female fertility: The number of babies per woman (<a href="https://data.worldbank.org/indicator/SP.DYN.TFRT.IN" class="uri">https://data.worldbank.org/indicator/SP.DYN.TFRT.IN</a>)</li>
<li>Primary school enrollment as % of children attending primary school (<a href="https://data.worldbank.org/indicator/SE.PRM.NENR" class="uri">https://data.worldbank.org/indicator/SE.PRM.NENR</a>)</li>
<li>Mortality rate, for under 5, per 1000 live births (<a href="https://data.worldbank.org/indicator/SH.DYN.MORT" class="uri">https://data.worldbank.org/indicator/SH.DYN.MORT</a>)</li>
<li>HIV prevalence (adults_with_hiv_percent_age_15_49.csv): The estimated number of people living with HIV per 100 population of age group 15-49.</li>
</ul>
<p>You must use the <code>wbstats</code> package to download data from the World Bank. The relevant World Bank indicators are <code>SP.DYN.TFRT.IN</code>, <code>SE.PRM.NENR</code>, <code>NY.GDP.PCAP.KD</code>, and <code>SH.DYN.MORT</code></p>
<pre class="r"><code># load gapminder HIV data
hiv &lt;- read_csv(here::here(&quot;data&quot;,&quot;adults_with_hiv_percent_age_15_49.csv&quot;))
life_expectancy &lt;- read_csv(here::here(&quot;data&quot;,&quot;life_expectancy_years.csv&quot;))

# get World bank data using wbstats
indicators &lt;- c(&quot;SP.DYN.TFRT.IN&quot;,&quot;SE.PRM.NENR&quot;, &quot;SH.DYN.MORT&quot;, &quot;NY.GDP.PCAP.KD&quot;)

library(wbstats)

worldbank_data &lt;- wb_data(country=&quot;countries_only&quot;, #countries only- no aggregates like Latin America, Europe, etc.
                          indicator = indicators, 
                          start_date = 1960, 
                          end_date = 2016)

# get a dataframe of information regarding countries, indicators, sources, regions, indicator topics, lending types, income levels,  from the World Bank API 
countries &lt;-  wbstats::wb_cachelist$countries
worldbank_data &lt;- inner_join(worldbank_data, countries, by = &quot;country&quot;)</code></pre>
<p>You have to join the 3 dataframes (life_expectancy, worldbank_data, and HIV) into one. You may need to tidy your data first and then perform <a href="http://r4ds.had.co.nz/relational-data.html">join operations</a>.</p>
<pre class="r"><code>#tidy HIV data
tidy_hiv &lt;- hiv %&gt;% 
  pivot_longer(
    cols = 2:34,
    names_to = &quot;Year&quot;,
    values_to = &quot;Adult_hiv_percent&quot;)

#tidy life expectancy data
tidy_life_expectancy &lt;- life_expectancy %&gt;% 
  pivot_longer(
    col = 2:302,
    names_to = &quot;Year&quot;,
    values_to = &quot;Life_expectancy&quot;)

#tidy worldbank date
tidy_worldbank_data &lt;- worldbank_data %&gt;%
  mutate(Year = as.character(date)) %&gt;% 
  rename(GDP_per_capita = NY.GDP.PCAP.KD,
         Female_fertility = SP.DYN.TFRT.IN,
         Primary_school_enrollment = SE.PRM.NENR,
         Mortality_rate = SH.DYN.MORT)

#firstly join HIV and life expectancy data; then join with worldbank data all using country and year
joined_data &lt;- list(tidy_hiv, tidy_life_expectancy, tidy_worldbank_data) %&gt;% 
  reduce(inner_join, by = c(&quot;country&quot;, &quot;Year&quot;))</code></pre>
<blockquote>
<p>Think about what type makes the most sense <strong>and explain why you chose it</strong>.</p>
</blockquote>
<p>We used inner_join to join 3 dataframes because inner_join would take intersection of different dataframes and ensure we can perform the following relationship analyses with required data. Although some observations have NA entries and are still included in the joined data, we have excluded such NA entries and the perform the analyses. 
Also, we are using inner_join() because it joins dataframes according to the provided condition. In this case, only observations with the same country and year available would be joined together. </p>
<ol style="list-style-type: decimal">
<li>What is the relationship between HIV prevalence and life expectancy? Generate a scatterplot with a smoothing line to report your results. You may find faceting useful</li>
</ol>
<pre class="r"><code>HIV_Life &lt;- joined_data %&gt;% 
  #clear out all NA
  filter(!is.na(Adult_hiv_percent))

ggplot(HIV_Life, 
       aes(x = Adult_hiv_percent,
           y = Life_expectancy))+
  geom_point(alpha=0.3)+
  geom_smooth(method = &quot;lm&quot;, formula = y ~ x)+
  theme_bw()+
  labs(
    title = &quot;Relationship between HIV prevalence and life expectancy&quot;,
    subtitle = &quot;&quot;,
    x = &quot;% Adults between 15 and 49 with HIV&quot;,
    y = &quot;Life expectancy (ages)&quot;
  )+
  facet_wrap(vars(region))+
  #to remove the skewness on a-axis
  scale_x_log10() </code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/relationship%20between%20HIV%20prevalence%20and%20life%20expectancy-1.png" width="960" style="display: block; margin: auto;" />
Generally, there is a negative relationship between HIV prevalence and Life Expectancy. When there are more people between 15 and 49 getting HIV, the life expectancy of that country would decrease. Such trend is most evident in regions like Latin America, Sub-Saharan Africa and Middle East &amp; North Africa.
However, for Europe and Central Asia, the trend has been positive. It does not suggest that more HIV cases would boost life expectancy. It might be attributed to the local healthcare improvement and higher budget for healthcare.</p>
<ol start="2" style="list-style-type: decimal">
<li>What is the relationship between fertility rate and GDP per capita? Generate a scatterplot with a smoothing line to report your results. You may find facetting by region useful</li>
</ol>
<pre class="r"><code>Fert_GDP &lt;- joined_data %&gt;% 
  #clear out all NA
  filter(!is.na(Female_fertility))

ggplot(Fert_GDP, 
       aes(x = GDP_per_capita,
           y = Female_fertility
           ))+
  geom_point(alpha=0.3)+
  geom_smooth(method = &quot;lm&quot;, formula = y ~ x)+
  theme_bw()+
  labs(
    title = &quot;Relationship between GDP per capita and Female fertility&quot;,
    subtitle = &quot;&quot;,
    x = &quot;GDP per capita (constant 2010 US$)&quot;,
    y = &quot;Female fertility (births per woman)&quot;
  )+
  facet_wrap(vars(region))+
  #to remove the skewness on a-axis
  scale_x_log10() </code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/relationship%20between%20GDP%20per%20capita%20and%20female%20fertility-1.png" width="960" style="display: block; margin: auto;" />
Generally, the relationship between GDP per capita and Female fertility is negative. This trend is evident in most regions but North America. There are many explanations:</p>
<ul>
<li>Firstly, the relative value of time to females in countries with different GDP per capita are extremely different. Higher GDP per capita would motivate females to work instead of staying at home and raising kids.</li>
<li>Secondly, in countries with higher GDP per capita, the expense to raise and educate a child is far higher than that in low-GDP countries. The competition in higher-GDP countries is also far more fierce, causing parents spending too much money on education.</li>
<li>Thirdly, with high GDP per capita and higher personal income, females would have more choices other than marriage and child-bearing. They would have higher tendency to pursue personal aspirations and left less time for having many children.</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Which regions have the most observations with missing HIV data? Generate a bar chart (<code>geom_col()</code>), in descending order.</li>
</ol>
<pre class="r"><code>#count missing HIV values
Missing_HIV &lt;- joined_data %&gt;% 
  group_by(region) %&gt;% 
  count(Adult_hiv_percent = NA) %&gt;% 
  mutate(n)

ggplot(Missing_HIV, 
       aes(reorder(region, -n),
           n))+
  geom_col()+
  labs(
    title = &quot;Missing observations of HIV data in each Continent&quot;,
    x= &quot;Region&quot;,
    y = &quot;Count of missing HIV data&quot;)</code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/most%20observations%20with%20missing%20HIV%20data-1.png" width="648" style="display: block; margin: auto;" />
The Sub-Saharan Africa region has the most missing HIV data in the dataframe. The plot above shows the descending order of missing HIV data of each region.</p>
<ol start="4" style="list-style-type: decimal">
<li>How has mortality rate for under 5 changed by region? In each region, find the top 5 countries that have seen the greatest improvement, as well as those 5 countries where mortality rates have had the least improvement or even deterioration.</li>
</ol>
<pre class="r"><code>#clear out all NA
Mortality_plot &lt;- joined_data %&gt;% 
  filter(!is.na(Mortality_rate))

ggplot(Mortality_plot, 
       aes(x = Year,
           y = Mortality_rate,
           color = region
           ))+
  geom_point(alpha=0.3)+
  theme_bw()+
  labs(
    title = &quot;Changes of Mortality rate for under 5 across regions&quot;,
    subtitle = &quot;&quot;,
    x = &quot;Year&quot;,
    y = &quot;Mortality rate for under 5 (per 1000 living births)&quot;)+
  facet_wrap(vars(region))+
  #to remove the skewness on a-axis
  scale_x_discrete(breaks=seq(1900, 2020, 5))</code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/regional%20difference%20in%20mortality%20rate%20for%20under%205-1.png" width="960" style="display: block; margin: auto;" />
For Mortality rate for under 5 of different regions, there are huge differences in their changes over time.</p>
<ul>
<li>For North America, such rate has been remaining in very low level since 1979.</li>
<li>For East Asia, Middle East &amp; North Africa, Europe and Latin America, even though in 1979 the mortality rate was in high levels, it has been decreasing since 1979 to approximately half of the initial level.</li>
<li>For South Asia, the mortality rate in 1979 was higher than the rate in East Asia. But through the development since then, the mortality rate has also reduced to half of its level.</li>
<li>For Sub-Saharan Africa, the mortality rate in 1979 has remained the highest among all regions since then. Within the region, the national differences are huge as well. Even in 2011, there are still countries where 150 new births out of 1000 would die before the age of 5.</li>
</ul>
<pre class="r"><code>Mortality_rank &lt;- joined_data %&gt;% 
  group_by(country) %&gt;% 
  mutate(
    #calculate yearly percentage change in mortality rate
    difference_of_rate = (Mortality_rate - lag(Mortality_rate))/lag(Mortality_rate)*100,
    #define initial level
    First = head(Mortality_rate, 1),
    #calculate 1979-2011 overall change in mortality rate
    BaselineChange = case_when(Mortality_rate != First ~ (Mortality_rate - First)/First*100,
                               TRUE ~ 1 * NA)) %&gt;% 
  filter(Year == 2011, !is.na(BaselineChange)) %&gt;% 
  select(country, region, BaselineChange) %&gt;% 
  group_by(region)

Minimum_change_list &lt;- Mortality_rank %&gt;% 
  slice_max(order_by = BaselineChange, n = 5) %&gt;% 
  knitr::kable(bootstrap_options = c (&quot;striped&quot;,&quot;hover&quot;,&quot;condensed&quot;,&quot;responsive&quot;), caption = &quot;Top 5 countries in each region seeing the smallest changes in mortality rate&quot;)
Minimum_change_list</code></pre>
<table>
<caption>(#tab:top 5 and bottom 5 countries in each region)Top 5 countries in each region seeing the smallest changes in mortality rate</caption>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="left">region</th>
<th align="right">BaselineChange</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Papua New Guinea</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-48.4</td>
</tr>
<tr class="even">
<td align="left">Fiji</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-49.2</td>
</tr>
<tr class="odd">
<td align="left">Myanmar</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-57.5</td>
</tr>
<tr class="even">
<td align="left">Philippines</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-61.1</td>
</tr>
<tr class="odd">
<td align="left">New Zealand</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-62.7</td>
</tr>
<tr class="even">
<td align="left">Bulgaria</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-58.2</td>
</tr>
<tr class="odd">
<td align="left">Switzerland</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-58.3</td>
</tr>
<tr class="even">
<td align="left">Ukraine</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-59.3</td>
</tr>
<tr class="odd">
<td align="left">Denmark</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-60.2</td>
</tr>
<tr class="even">
<td align="left">Netherlands</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-61.6</td>
</tr>
<tr class="odd">
<td align="left">Trinidad and Tobago</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-45.3</td>
</tr>
<tr class="even">
<td align="left">Barbados</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-47.9</td>
</tr>
<tr class="odd">
<td align="left">Guyana</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-48.2</td>
</tr>
<tr class="even">
<td align="left">Panama</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-57.0</td>
</tr>
<tr class="odd">
<td align="left">Jamaica</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-58.0</td>
</tr>
<tr class="even">
<td align="left">Djibouti</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-53.3</td>
</tr>
<tr class="odd">
<td align="left">Malta</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-61.4</td>
</tr>
<tr class="even">
<td align="left">Qatar</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-76.6</td>
</tr>
<tr class="odd">
<td align="left">Israel</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-77.0</td>
</tr>
<tr class="even">
<td align="left">Morocco</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-78.1</td>
</tr>
<tr class="odd">
<td align="left">United States</td>
<td align="left">North America</td>
<td align="right">-53.8</td>
</tr>
<tr class="even">
<td align="left">Canada</td>
<td align="left">North America</td>
<td align="right">-57.9</td>
</tr>
<tr class="odd">
<td align="left">Pakistan</td>
<td align="left">South Asia</td>
<td align="right">-49.0</td>
</tr>
<tr class="even">
<td align="left">Afghanistan</td>
<td align="left">South Asia</td>
<td align="right">-66.1</td>
</tr>
<tr class="odd">
<td align="left">India</td>
<td align="left">South Asia</td>
<td align="right">-68.2</td>
</tr>
<tr class="even">
<td align="left">Bangladesh</td>
<td align="left">South Asia</td>
<td align="right">-77.3</td>
</tr>
<tr class="odd">
<td align="left">Sri Lanka</td>
<td align="left">South Asia</td>
<td align="right">-77.5</td>
</tr>
<tr class="even">
<td align="left">Central African Republic</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-23.6</td>
</tr>
<tr class="odd">
<td align="left">Lesotho</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-26.0</td>
</tr>
<tr class="even">
<td align="left">Zimbabwe</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-26.0</td>
</tr>
<tr class="odd">
<td align="left">Nigeria</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-38.1</td>
</tr>
<tr class="even">
<td align="left">Chad</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-40.1</td>
</tr>
</tbody>
</table>
<pre class="r"><code>Maximum_change_list &lt;- Mortality_rank %&gt;% 
  slice_min(order_by = BaselineChange, n = 5) %&gt;% 
  knitr::kable(bootstrap_options = c (&quot;striped&quot;,&quot;hover&quot;,&quot;condensed&quot;,&quot;responsive&quot;), caption = &quot;Top 5 countries in each region seeing the largest changes in mortality rate&quot;)
Maximum_change_list</code></pre>
<table>
<caption>(#tab:top 5 and bottom 5 countries in each region)Top 5 countries in each region seeing the largest changes in mortality rate</caption>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="left">region</th>
<th align="right">BaselineChange</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Mongolia</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-83.2</td>
</tr>
<tr class="even">
<td align="left">Singapore</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-81.3</td>
</tr>
<tr class="odd">
<td align="left">Cambodia</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-80.3</td>
</tr>
<tr class="even">
<td align="left">Thailand</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-79.5</td>
</tr>
<tr class="odd">
<td align="left">China</td>
<td align="left">East Asia &amp; Pacific</td>
<td align="right">-77.7</td>
</tr>
<tr class="even">
<td align="left">Portugal</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-87.5</td>
</tr>
<tr class="odd">
<td align="left">Turkey</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-87.3</td>
</tr>
<tr class="even">
<td align="left">Greece</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-81.4</td>
</tr>
<tr class="odd">
<td align="left">Georgia</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-78.8</td>
</tr>
<tr class="even">
<td align="left">Luxembourg</td>
<td align="left">Europe &amp; Central Asia</td>
<td align="right">-78.4</td>
</tr>
<tr class="odd">
<td align="left">Peru</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-85.3</td>
</tr>
<tr class="even">
<td align="left">El Salvador</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-83.7</td>
</tr>
<tr class="odd">
<td align="left">Brazil</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-82.2</td>
</tr>
<tr class="even">
<td align="left">Ecuador</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-81.8</td>
</tr>
<tr class="odd">
<td align="left">Nicaragua</td>
<td align="left">Latin America &amp; Caribbean</td>
<td align="right">-80.0</td>
</tr>
<tr class="even">
<td align="left">Oman</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-90.4</td>
</tr>
<tr class="odd">
<td align="left">Algeria</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-83.6</td>
</tr>
<tr class="even">
<td align="left">Tunisia</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-82.3</td>
</tr>
<tr class="odd">
<td align="left">Lebanon</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-81.0</td>
</tr>
<tr class="even">
<td align="left">Morocco</td>
<td align="left">Middle East &amp; North Africa</td>
<td align="right">-78.1</td>
</tr>
<tr class="odd">
<td align="left">Canada</td>
<td align="left">North America</td>
<td align="right">-57.9</td>
</tr>
<tr class="even">
<td align="left">United States</td>
<td align="left">North America</td>
<td align="right">-53.8</td>
</tr>
<tr class="odd">
<td align="left">Maldives</td>
<td align="left">South Asia</td>
<td align="right">-91.8</td>
</tr>
<tr class="even">
<td align="left">Bhutan</td>
<td align="left">South Asia</td>
<td align="right">-80.2</td>
</tr>
<tr class="odd">
<td align="left">Nepal</td>
<td align="left">South Asia</td>
<td align="right">-79.4</td>
</tr>
<tr class="even">
<td align="left">Sri Lanka</td>
<td align="left">South Asia</td>
<td align="right">-77.5</td>
</tr>
<tr class="odd">
<td align="left">Bangladesh</td>
<td align="left">South Asia</td>
<td align="right">-77.3</td>
</tr>
<tr class="even">
<td align="left">Rwanda</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-75.5</td>
</tr>
<tr class="odd">
<td align="left">Eritrea</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-72.8</td>
</tr>
<tr class="even">
<td align="left">Malawi</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-70.3</td>
</tr>
<tr class="odd">
<td align="left">Senegal</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-70.3</td>
</tr>
<tr class="even">
<td align="left">Ethiopia</td>
<td align="left">Sub-Saharan Africa</td>
<td align="right">-67.7</td>
</tr>
</tbody>
</table>
<ol start="5" style="list-style-type: decimal">
<li>Is there a relationship between primary school enrollment and fertility rate?</li>
</ol>
<pre class="r"><code>#clear out all NA
Fert_PrimEnrol &lt;- joined_data %&gt;% 
  filter(!is.na(Primary_school_enrollment), !is.na(Female_fertility))

ggplot(Fert_PrimEnrol, 
       aes(x = Primary_school_enrollment,
           y = Female_fertility))+
  geom_point(alpha=0.3)+
  geom_smooth(method = &quot;lm&quot;,
              formula = y ~ x)+
  theme_bw()+
  labs(
    title = &quot;Relationship between Primary School Enrollment and Female fertility&quot;,
    subtitle = &quot;&quot;,
    x = &quot;Primary School Enrollment (% net)&quot;,
    y = &quot;Female fertility (births per woman)&quot;
  )+
  facet_wrap(vars(region))+
  #to remove the skewness on axes
  scale_x_log10()+
  scale_y_log10()</code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/relationship%20between%20primary%20school%20enrollment%20and%20female%20fertility-1.png" width="648" style="display: block; margin: auto;" />
Generally, there is a negative relationship between primary school enrollment and female fertility. However, it is also worth noting that such relationship is less significant in Europe &amp; Central Asia. There are a huge cluster of observations on the right of the distribution and the best fitting line is actually positive sloping. Here are some possible explanations for the negative trend in regions such as Sub-Saharan Africa and Middle East:</p>
<ul>
<li>Firstly, primary school enrollment could be used as a proxy for national development, wealthiness and cultural value in education. In countries with higher primary school enrollment, it can be expected that females could spend more time pursuing personal goals and spend less time having kids.</li>
<li>Secondly, higher primary school enrollment could help promote maternal and child health. Literacy developed in primary school would largely help females read and understand labels or caveats on drug bottles or on many instructions. Therefore, they wouldn’t need to give birth to many children.</li>
<li>Thirdly, having primary school education would help postpone marriage for many teenage girls, especially in rural and less developed areas. Being older getting into marriage, females would on average have less probability in having kids.</li>
</ul>
</div>
<div id="challenge-1-excess-rentals-in-tfl-bike-sharing" class="section level1">
<h1>Challenge 1: Excess rentals in TfL bike sharing</h1>
<p>Recall the TfL data on how many bikes were hired every single day. We can get the latest data by running the following</p>
<pre class="r"><code>url &lt;- &quot;https://data.london.gov.uk/download/number-bicycle-hires/ac29363e-e0cb-47cc-a97a-e216d900a6b0/tfl-daily-cycle-hires.xlsx&quot;

# Download TFL data to temporary file
httr::GET(url, write_disk(bike.temp &lt;- tempfile(fileext = &quot;.xlsx&quot;)))</code></pre>
<pre><code>## Response [https://airdrive-secure.s3-eu-west-1.amazonaws.com/london/dataset/number-bicycle-hires/2021-08-23T14%3A32%3A29/tfl-daily-cycle-hires.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAJJDIMAIVZJDICKHA%2F20210920%2Feu-west-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20210920T122824Z&amp;X-Amz-Expires=300&amp;X-Amz-Signature=f6427fd15483602769b22b08d854cb78075b2c4a77c827b6039e39b3f2ee2eb7&amp;X-Amz-SignedHeaders=host]
##   Date: 2021-09-20 12:28
##   Status: 200
##   Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
##   Size: 173 kB
## &lt;ON DISK&gt;  C:\Users\ursig\AppData\Local\Temp\Rtmp40pS3A\file1e9c5c1450e1.xlsx</code></pre>
<pre class="r"><code># Use read_excel to read it as dataframe
bike0 &lt;- read_excel(bike.temp,
                   sheet = &quot;Data&quot;,
                   range = cell_cols(&quot;A:B&quot;))

# change dates to get year, month, and week
bike &lt;- bike0 %&gt;% 
  clean_names() %&gt;% 
  rename (bikes_hired = number_of_bicycle_hires) %&gt;% 
  mutate (year = year(day),
          month = lubridate::month(day, label = TRUE),
          week = isoweek(day))</code></pre>
<p>We can easily create a facet grid that plots bikes hired by month and year.</p>
<p><img src="C:/Users/ursig/OneDrive/Desktop/Statistics_LBS/new_website/images/tfl_distributions_monthly.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Look at May and Jun and compare 2020 with the previous years. What’s happening?
The curves are flattening in May and June 2020 compared to previous years, implying less bikes are being rented per day. In early 2020 Covid-19 hit the world and the first wave of infections arrived around April and May 2020. People were put in an unprecedented situation with living through a pandemic. Many people were afraid to go out, in fear of catching the virus, the consequences of which have not yet been fully researched.
In a world where people are generally afraid of going out, it is likely that people also don’t want to rent public bikes which have been used by numerous individuals that could potentially carry the virus. Consequently, bike rentals in May and June went down with people trying to touch as little as possible things to reduce the likelihood of catching the virus.</p>
<p>However, the challenge I want you to work on is to reproduce the following two graphs.</p>
<p><img src="C:/Users/ursig/OneDrive/Desktop/Statistics_LBS/new_website/images/tfl_monthly.png" width="100%" style="display: block; margin: auto;" /></p>
<p>The second one looks at percentage changes from the expected level of weekly rentals. The two grey shaded rectangles correspond to Q2 (weeks 14-26) and Q4 (weeks 40-52).</p>
<p><img src="C:/Users/ursig/OneDrive/Desktop/Statistics_LBS/new_website/images/tfl_weekly.png" width="100%" style="display: block; margin: auto;" /></p>
<p>For both of these graphs, you have to calculate the expected number of rentals per week or month between 2016-2019 and then, see how each week/month of 2020-2021 compares to the expected rentals. Think of the calculation <code>excess_rentals = actual_rentals - expected_rentals</code>.</p>
<pre class="r"><code>#Compute expected average bike rentals in each month
exp_bikes_per_month &lt;- bike %&gt;%
  filter(year %in% 2016:2019) %&gt;%
  group_by(month) %&gt;%
  summarize(
    monthly_average = mean(bikes_hired)
  )
#Compute actual average bike rentals per month
actual_bikes_per_month &lt;- bike %&gt;%
  filter(year&gt;=2016) %&gt;%
  group_by(year, month) %&gt;%
  summarize(
    act_monthly_average = mean(bikes_hired)
  )
#Merge actual and expected bike rental in one dataframe
bikes_per_month &lt;- 
  left_join(actual_bikes_per_month, exp_bikes_per_month, by=&quot;month&quot;)

#Compute discrepancies in actual and expected bike rentals
bikes_per_month &lt;- bikes_per_month %&gt;%
  mutate(
    excess_rentals = act_monthly_average - monthly_average,
    up = ifelse(act_monthly_average&gt;monthly_average, excess_rentals, 0),
    down = ifelse(act_monthly_average&lt;monthly_average, excess_rentals, 0)
  )

ggplot(bikes_per_month, aes(x=month, group = year))+
  geom_line(aes(y=act_monthly_average),size=0.4)+
  geom_line(aes(y=monthly_average), size=1, color=&quot;blue&quot;) +
  facet_wrap(~year)+
  theme_minimal()+
  geom_ribbon(aes(ymin=monthly_average,ymax=monthly_average+up), fill=&quot;#CB454A&quot;,alpha=0.4)+
  geom_ribbon(aes(ymin=monthly_average+down,ymax=monthly_average),fill=&quot;#7DCD85&quot;,alpha=0.4)+
  labs(
    title=&quot;Monthly changes in TfL bike rentals&quot;,
    subtitle=&quot;Change from monthly average
shown in blue and calculated between 2016-2019&quot;,
    y=&quot;Bike rentals&quot;,
    x=&quot;&quot;,
    caption = &quot;Source: TfL, London Data Store&quot;
  )+
  theme(plot.title = element_text(size=14),
        plot.subtitle=element_text(size = 12),
        axis.title.y = element_text(face=&quot;bold&quot;))</code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/Monthly%20changes%20in%20TfL%20bike%20rentals-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Compute expected weekly average bike rentals in each month
exp_bikes_per_week &lt;- bike %&gt;%
  filter(year&gt;=2016 &amp; year &lt;=2019) %&gt;%
  group_by(week) %&gt;%
  summarize(
    weekly_average = mean(bikes_hired)
  )

#Compute actual average bike rentals per week
actual_bikes_per_week &lt;- bike %&gt;%
  filter(year&gt;=2016) %&gt;%
  group_by(week,year) %&gt;%
  summarize(
    act_weekly_average = mean(bikes_hired)
  )
#Merge actual and expected bike rental in one dataframe
bikes_per_week &lt;- 
  left_join(actual_bikes_per_week, exp_bikes_per_week, by=&quot;week&quot;)

#Compute discrepancies in actual and expected bike rentals. In addition, 
#take out week 53 for 2021.
bikes_per_week &lt;- bikes_per_week %&gt;%
  filter(!(week==53 &amp; year==2021)) %&gt;%
  mutate(
    excess_rentals = (act_weekly_average - weekly_average) / weekly_average,
    up = if_else(excess_rentals&gt;0, excess_rentals,0),
    down = if_else(excess_rentals &lt; 0, excess_rentals,0)
  )
#Plot graph
ggplot(bikes_per_week,aes(x=week))+
         geom_line(aes(y=excess_rentals))+
  facet_wrap(~year)+
  theme_minimal()+
  geom_ribbon(aes(ymin=down,ymax=0),
              fill=&quot;#CB454A&quot;,
              alpha=0.4)+
  geom_ribbon(aes(ymin=0, ymax=up), 
              fill=&quot;#7DCD85&quot;, 
              alpha=0.4)+
  geom_rug(data=subset(bikes_per_week, excess_rentals &gt; 0), 
           sides=&quot;b&quot;, 
           color=&quot;#7DCD85&quot;)+
  geom_rug(data=subset(bikes_per_week, excess_rentals &lt; 0), 
           sides=&quot;b&quot;, 
           color=&quot;#CB454A&quot;)+
  annotate(geom = &quot;rect&quot;, xmin = 14, xmax = 26, ymin = -Inf, ymax = Inf, fill = &quot;grey&quot;, alpha=0.3)+
  annotate(geom = &quot;rect&quot;, xmin = 40, xmax = 52, ymin = -Inf, ymax = Inf, fill = &quot;grey&quot;, alpha=0.3)+
  scale_y_continuous(breaks=seq(-0.5,1,0.5),labels=function(x) paste0(x*100, &quot;%&quot;),limits=c(-0.6,1))+
  labs(
    title=&quot;Weekly changes in TfL bike rentals&quot;,
    subtitle=&quot;% change from weekly averages
calculated between 2016-2019&quot;,
    y=&quot;&quot;,
    x=&quot;week&quot;,
    caption = &quot;Source: TfL, London Data Store&quot;
  )+
  theme(plot.title = element_text(face=&quot;bold&quot;,size=14),
        plot.subtitle=element_text(face=&quot;bold&quot;,size=12))</code></pre>
<p><img src="/blogs/homework2_second_draft_files/figure-html/Weekly%20changes%20in%20TfL%20bike%20rentals-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Should you use the mean or the median to calculate your expected rentals? Why?
Generally speaking, expected values are computed by using the mean. The mean takes into account all values, even outliers, and therefore provides a good estimation of future values. The median also takes into account all values, but chooses the middle value, which might not accurately present future data. 
Just in very skewed distributions, it might make sense to use the median to prevent outliers from skewing data, but I believe in this case the mean should be the most precise metrics. Furthermore, those two graphs were using the average, we used the same in order to properly replicate the graph.</p>
<p>In creating your plots, you may find these links useful:</p>
<ul>
<li><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_ribbon.html</a></li>
<li><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_tile.html</a></li>
<li><a href="https://ggplot2.tidyverse.org/reference/geom_rug.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_rug.html</a></li>
</ul>
</div>
<div id="deliverables" class="section level1">
<h1>Deliverables</h1>
<p>As usual, there is a lot of explanatory text, comments, etc. You do not need these, so delete them and produce a stand-alone document that you could share with someone. Knit the edited and completed R Markdown file as an HTML document (use the “Knit” button at the top of the script editor window) and upload it to Canvas.</p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: Jiangxia Yu; Marianna Taki; Yuting Wu; Ferdinand Wohlenberg; Massimiliano Ursig; Tanisha Yadav</li>
<li>Approximately how much time did you spend on this problem set: ANSWER HERE</li>
<li>What, if anything, gave you the most trouble: ANSWER HERE</li>
</ul>
<p><strong>Please seek out help when you need it,</strong> and remember the <a href="https://mam202.netlify.app/syllabus/#the-15-minute-rule" target="_blank">15-minute rule</a>. You know enough R (and have enough examples of code from class and your readings) to be able to do this. If you get stuck, ask for help from others, post a question on Slack– and remember that I am here to help too!</p>
<blockquote>
<p>As a true test to yourself, do you understand the code you submitted and are you able to explain it to someone else?</p>
</blockquote>
</div>
<div id="rubric" class="section level1">
<h1>Rubric</h1>
<p>Check minus (1/5): Displays minimal effort. Doesn’t complete all components. Code is poorly written and not documented. Uses the same type of plot for each graph, or doesn’t use plots appropriate for the variables being analyzed.</p>
<p>Check (3/5): Solid effort. Hits all the elements. No clear mistakes. Easy to follow (both the code and the output).</p>
<p>Check plus (5/5): Finished all components of the assignment correctly and addressed both challenges. Code is well-documented (both self-documented and with additional comments as necessary). Used tidyverse, instead of base R. Graphs and tables are properly labelled. Analysis is clear and easy to follow, either because graphs are labeled clearly or you’ve written additional text to describe how you interpret the output.</p>
</div>
